name: Pollen Forecast Alert

on:
  schedule:
    # Runs at 7:00 AM UTC every day (8-9 AM Central European Time depending on daylight saving)
    - cron: '0 7 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run pollen forecast scraper and send email
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        USE_SSL: ${{ secrets.USE_SSL }}
        SMTP_AUTH_REQUIRED: ${{ secrets.SMTP_AUTH_REQUIRED }}
        CITY_NAME: ${{ secrets.CITY_NAME }}
        SENDER_NAME: ${{ secrets.SENDER_NAME }}
        LANGUAGE: ${{ secrets.LANGUAGE }}
      run: |
        python pollen_scraper.py
